puts "🌱 Seeding spices..."

# Seed your database here
Recipe.create(image_url:"https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",name:"Apam balik",category:"Dessert",instructions:"Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly. Spread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear. Add butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned. Cut into wedges and best eaten when it is warm.")
Recipe.create(image_url:"https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",name:"Baingan Bharta",category:"Vegetarian",instructions:"Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and keep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won't get the smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly cooked. You could also embed some garlic cloves in the baingan and then roast it. 2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid easily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools down. 3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step. Use natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red. 4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted aubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke. 5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the charcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will become. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is cooked, just like the way we do for Dal Tadka. 6. Peel the skin from the roasted and smoked eggplant. 7. Chop the cooked eggplant finely or you can even mash it. 8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic. 9. Saute the onions till translucent. Don't brown them. 10. Add chopped green chilies and saute for a minute. 11. Add the chopped tomatoes and mix it well. 12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture. 13. Now add the red chili powder. Stir and mix well. 14. Add the chopped cooked baingan. 15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture. 16. Season with salt. Stir and saute for some more 4 to 5 minutes more. 17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with phulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.")
Recipe.create(image_url:"https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg",name:"Banana Pancakes",category:"Dessert",instructions:"In a bowl, mash the banana with a fork until it resembles a thick purée. Stir in the eggs, baking powder and vanilla. Heat a large non-stick frying pan or pancake pan over a medium heat and brush with half the oil. Using half the batter, spoon two pancakes into the pan, cook for 1-2 mins each side, then tip onto a plate. Repeat the process with the remaining oil and batter. Top the pancakes with the pecans and raspberries.")
Recipe.create(image_url:"https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",name:"Burek",category:"Side",instructions:"Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.")
Recipe.create(image_url:"https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg",name:"Kumpir",category:"Side",instructions:"If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer. Grate (roughly – you can use as much as you like) 150g of cheese. Finely chop one onion and one sweet red pepper. Put these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).")

User.create(name:"Mackenzie",email:"mackenzie@gmail.com")
User.create(name:"Joe Doe", email:"joe@gmail.com")
User.create(name:"Jayden", email:"jayden@gmail.com")

Review.create(description:"Hats off this is by far the best turkey recipe i have ever used.", user_id:1, recipe_id:4, created_at:"", updated_at:"")
Review.create(description:"I have used this recipe for almost 5 years now. It just gets better and better every time it is a perfection.", user_id:3, recipe_id:2, created_at:"", updated_at:"")
Review.create(description:"This recipe is a perfect marriage of meat,sweet and heat the balance is spot on. I only wish i had doubled the recipe because it was so ull of flavour.", user_id:2, recipe_id:2,  created_at:"", updated_at:"")
Review.create(description:"This recipe is a hit on the head. The sauce is smooh with just the right tang of lemon. My friends have begged me to make one for them.", user_id:2, recipe_id:3, created_at:"", updated_at:"")
Review.create(description:"This is the most moist and balanced cake i have ever attempted! It is not oversweet  norit is gooey", user_id:1, recipe_id:1, created_at:"", updated_at:"")
Review.create(description:"Tis is the best recipe out there,hands down. I can sit and eat te whole bowl by myself.", user_id:2, recipe_id:"5",  created_at:"", updated_at:"")
Review.create(description:"Easy and delicious.You don't need a long grocery list.",  user_id:3, recipe_id:2, created_at:"", updated_at:"")
Review.create(description:"Excellent very easy to prepare and juicy . THanks for the recipe.", user_id:1, recipe_id:4, created_at:"", updated_at:"")
Review.create(description:"This is really great! I keep looking for new recipes for chicken this one is definetely a five star.", user_id:3, recipe_id:4,  created_at:"", updated_at:"")
puts "✅ Done seeding!"
